toml

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "kmerRRR"
version = "0.1.0"
license = "MIT"
license-file = "LICENSE"
authors = [ { name = "Jabale Rahmat", email = "jrahmat@ur.rochester.edu" } ]
description = "A k-mer based tool to enhance functional genomics in Repeat Reach Regions"
dependencies = [ "numpy", "biopython", "scipy", "pysam", "matplotlib", "pyjellyfish" ]
readme = "ReadMe_kmerRRR_0.1.0.md"
requires-python = ">=3.7"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
kmerRRR = ["kmerRRR/R/*.R"]
